## **General**
1- What's the difference between a Machine Learning (ML) Model and a Machine Learning algorithm.

2- Why we need to study Linear Algebra for ML?

# Responses:
1-difference between a Machine Learning (ML) Model and a Machine Learning algorithm:

**An “algorithm” in machine learning is a procedure that is run on data to create a machine learning “model.”

**A “model” in machine learning is the output of a machine learning algorithm run on data.it represents what was learned by a machine learning algorithm



2-we need to study Linear Algebra for ML because Linear Algebra allows us to start understanding basic linear systems with use of matrices and vectors; which we need it in ML.

**## Vectors:**

**1- create a vector: **

Our vector can be written as v=(2,1), but more formally we would use the following notation, in which the dimensional coordinate values for the vector are shown as a matrix:$$\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}$$

In [1]:
import numpy as np
v=np.array([[2],
            [1]])

print(v)

[[2]
 [1]]


### **2-Calculating Magnitude**

In [5]:
import math
v=np.array([[2],
            [1]])
magnitude = math.sqrt(sum(j**2 for j in v))
print(magnitude)



2.23606797749979



**3- Vector Addition:**
So far, we've worked with one vector at a time. What happens when you need to add two vectors.

Let's take a look at an example, we already have a vector named v, as defined here:$$\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}$$Now let's create a second vector, and called s like this:$$\vec{s} = \begin{bmatrix}-3 \\ 2 \end{bmatrix}$$

And we have :$$\vec{z} = \vec{v}+\vec{s}$$

In [8]:

import math
import numpy as np

v = np.array([[2],
              [1]])
s = np.array([[-3],
              [2]]) 
z = np.add(v,s)
print (z)

[[-1]
 [ 3]]



4- Dot Product Multiplication


$$ \vec{d}=\vec{v} \cdot \vec{s} = (v_{1} \cdot s_{1}) + (v_{2} \cdot s_{2}) ... + \; (v_{n} \cdot s_{n})$$

In [11]:

import math
import numpy as np

v = np.array([[2],
              [1]])
s = np.array([[-3],
              [2]])  
d = v*s
print (d)

[[-6]
 [ 2]]


## **Matrices:**

# 1- create a Matrice:
A matrix arranges numbers into rows and columns, like this:

$$A = \begin{bmatrix}
  1 &amp; 2 &amp; 3 \\
  4 &amp; 5 &amp; 6
 \end{bmatrix}
$$

In [14]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
print (A)

[[1 2 3]
 [4 5 6]]



#2- Matrix Transposition
You can transpose a matrix, that is switch the orientation of its rows and columns. You indicate this with a superscript T, like this:

$$\begin{bmatrix}1 &amp; 2 &amp; 3 \\4 &amp; 5 &amp; 6\end{bmatrix}^{T} = \begin{bmatrix}1 &amp; 42 &amp; 53 &amp; 6 \end{bmatrix}$$

a- How can we do it mathematically? 

interchange the rows and columns of the matrix
i.e. write the elements of the rows as columns and write the elements of a column as rows.



b- with Python: 

In [20]:
import numpy as np

A=np.transpose(A)
print(A)

[[1 4]
 [2 5]
 [3 6]]


## **Eigendecomposition:**

So we've learned a little about eigenvalues and eigenvectors; but you may be wondering what use they are. Well, one use for them is to help decompose transformation matrices.

1- How can we decompose a matrix? ( Rules and steps)
2- (Bonus) Do it in python with your exampls.

1-........................................

In [27]:
#2 bonus
import numpy as np
A = np.array([[1,2],[2,2]])
eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvalues = np.diag(eigenvalues)
B = eigenvectors.dot(eigenvalues).dot(eigenvectors.T)
#B==A
print(eigenvalues)
print(eigenvectors)
print(B)


[[-0.56155281  0.        ]
 [ 0.          3.56155281]]
[[-0.78820544 -0.61541221]
 [ 0.61541221 -0.78820544]]
[[1. 2.]
 [2. 2.]]


***Git and github commands***

1-git init

2-git remote add origin https://github.com/ourdjiniaymen/AiSummerUniv2021

3-git add -A

4-git commit -m"test1"

5-git push origin master